name: AACAdditionPro
version: '${project.version}'
description: '${project.description}'
author: Photon

depend: [AAC, ProtocolLib]
main: de.photon.AACAdditionPro.AACAdditionPro

commands:
  aacadditionpro:
    description: The main command of AACAdditionPro.
    usage: /aacadditionpro
