name: AACAdditionPro
version: '${project.version}'
description: '${project.description}'
author: Photon

depend: [AAC, ProtocolLib]
main: de.photon.AACAdditionPro.AACAdditionPro

commands:
  aacadditionpro:
    description: The main command of AACAdditionPro.
    usage: /aacadditionpro
permissions:
  aacadditionpro.*:
    description: Gives access to all commands of AACAdditionPro except the verbose system
    children:
      aacadditionpro.info: true
      aacadditionpro.entitycheck: true
      aacadditionpro.neural: true
      aacadditionpro.neural.*: true
      aacadditionpro.tablistremove: true
  aacadditionpro.info:
    description: Allows to request an overview about a player's violation levels
  aacadditionpro.entitycheck:
    description: Allows to initiate a manual entity check
  aacadditionpro.neural:
    description: Grants basic access to the heuristics framework (see all active patterns and access the help)
  aacadditionpro.neural.*:
    description: Grants access to the full heuristics framework (config setting unlock_full_framework is still required)
    children:
      aacadditionpro.neural.create: true
      aacadditionpro.neural.train: true
  aacadditionpro.neural.create:
    description: Allows the creation and removal of patterns
  aacadditionpro.neural.train:
    description: Allows the training of patterns.
  aacadditionpro.tablistremove:
    description: Grants access to a command to temporarily remove a player from the tablist of another player.